name: build-schedule
on:
    schedule:
        - cron: '30 1 * * *' #01:30 Hour UTC = 08:30 Hour GMT+7
        - cron: '30 6 * * *' #06:30 Hour UTC = 13:30 Hour GMT+7
        - cron: '30 12 * * *' #12:30 Hour UTC = 19:30 Hour GMT+7
    workflow_dispatch:
jobs:
    vercel-build-schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger vercel build
              run: curl -X POST ${{secrets.VERCEL_HOOK}}
